# Start with debug middleware for gin
debug = false

# Listen port, default is 6043
port = 6043

# log level
loglevel = "info"

# go pool size
gopoolsize = 50000

# interval for TDengine metrics
RotationInterval = "15s"

[tdengine]
host = "192.168.13.170"
port = 6041
username = "root"
password = "iOURhvGntbb2hIoD"

# list of taosAdapter that need to be monitored
[taosAdapter]
address = ["127.0.0.1:6041","192.168.13.170:6041"]

[metrics]
# metrics prefix in metrics names.
prefix = "taos"

# database for storing metrics data
database = "log"

# export some tables that are not super table
tables = ["normal_table"]

[environment]
# Whether running in cgroup.
incgroup = false